@startuml

title SODALITE CI/CD pipeline:\nContinuous Delivery

actor "developer" as human


participant "Master branch" as master
participant "Jenkins\nautomation server" as jenkins
participant "SODALITE\nprivate registry" as private_registry
participant "sodaliteh2020\non Dockerhub" as dockerhub
participant "SODALITE Testbed" as testbed




group Staging
activate master
note over master: Release:\n0.2.9-beta\n(staging)

master -> jenkins: New tag available
activate jenkins

human --> jenkins: Build tag 0.2.9-beta
jenkins -> jenkins: Run unit tests


jenkins -> jenkins: Build images
activate private_registry
jenkins -> private_registry: Push images

activate testbed
deactivate private_registry
jenkins -> testbed: Deploy app to staging VM

jenkins --> human: success
deactivate testbed
deactivate jenkins
end



group Production

activate master

note over master: Release:\n0.2.9\n(production)


master -> jenkins: New tag available
activate jenkins

human --> jenkins: Build tag 0.2.9
jenkins -> jenkins: Run unit tests
jenkins -> jenkins: Build images
activate private_registry
jenkins -> private_registry: Push images
activate dockerhub
deactivate private_registry
jenkins -> dockerhub: Push images
activate testbed
deactivate dockerhub

jenkins -> testbed: Deploy app to production VM

jenkins --> human: success
deactivate testbed
deactivate jenkins
end




@enduml