@startuml

title SODALITE CI/CD pipeline\nStaging on every commit to master

actor "SODALITE\ndeveloper" as human

participant "Development branch" as dev
participant "Pull Request" as pr
participant "Master branch" as master
participant "Jenkins test server" as jenkins
participant "SODALITE\nprivate registry" as private_registry
participant "sodaliteh2020\non Dockerhub" as dockerhub
participant "SODALITE Testbed" as testbed

activate dev
activate jenkins

human -> dev: Commit
dev -> jenkins: Run unit tests
dev <- jenkins: OK

' human -> dev: Commit #2
' dev --> jenkins: Run unit tests
' dev <-- jenkins: fail
' ...
' human -> dev: Commit #n
' dev -> jenkins: Run unit tests
' dev <- jenkins: OK


dev -> pr: Submit pull request
deactivate dev
activate pr


pr -> jenkins: Run unit tests
pr <- jenkins: OK
pr -> master: Merge pull request
deactivate pr
activate master

master -> jenkins: Run unit tests
master <- jenkins: OK

group Staging
master -> jenkins: New commit
' deactivate master
jenkins -> jenkins: Run unit tests


jenkins -> jenkins: Build images
activate private_registry
jenkins -> private_registry: Push images
end


group Production
activate master

note over master: Release:\n0.2.9\n(production)


master -> jenkins: New tag available
deactivate master

human --> jenkins: Build tag 0.2.9
jenkins -> jenkins: Run unit tests
jenkins -> jenkins: Build images
jenkins -> private_registry: Push images
activate dockerhub
jenkins -> dockerhub: Push images
activate testbed
jenkins -> testbed: Deploy app
end




@enduml