@startuml

title SODALITE CI/CD pipeline:\nContinuous Integration

actor "developer\nauthor" as human
actor "developer\nreviewer" as human2

participant "Development\nbranch" as dev
participant "Pull\nRequest" as pr
participant "Master\nbranch" as master
participant "SonarCloud" as sonar
participant "Codacy" as codacy
participant "PR Labeler" as pr_labeler
participant "Release\nDrafter" as release_drafter
participant "Jenkins\nautomation\nserver" as jenkins


human -> dev: Commit
activate dev
dev -> jenkins: Run unit tests
activate jenkins
dev <-- jenkins: OK
deactivate jenkins

dev -> pr: Submit pull request
deactivate dev
activate pr


pr -> jenkins: Run unit tests
activate jenkins
pr <-- jenkins: OK
deactivate jenkins

pr -> sonar: Code Analysis
activate sonar
pr <-- sonar: passed
deactivate sonar

pr -> codacy: Request PR Quality Review
activate codacy
pr <-- codacy: OK
deactivate codacy

pr -> pr_labeler: Label PR
activate pr_labeler
pr <-- pr_labeler: Add label "feature"
deactivate pr_labeler

human -> pr: Add label "major"

pr -> human2: Request Review
activate human2
pr <-- human2: Code looks good
deactivate human2

pr -> master: Merge pull request
deactivate pr
activate master

master -> jenkins: Run unit tests
activate jenkins
master <-- jenkins: OK
deactivate jenkins

master -> sonar: Code Analysis
activate sonar
master <-- sonar: Quality Gate passed
deactivate sonar

master -> release_drafter: New PR Merged
activate release_drafter
master <-- release_drafter: New Release Draft
deactivate release_drafter
deactivate master






@enduml