@startuml

title Start application (WP5)

actor "Application\nOps Expert" as ops
participant "SODALITE\nIDE" as ide
participant  Orchestrator as orch
participant "Execution Platform \n (EP)" as res
participant "VM" as VM
participant "Component" as lre
participant "Monitoring Platform" as mon

ops->ide: Start application (application)

ide->orch: Start application (application)
activate ide

activate orch
par Startable components
  alt EP is IaaS Clouds (OpenStack, AWS)
    orch->VM: Start (component)
    VM->>lre: Start
  else EP is Kubernetes
    orch->res: Start (component)
    res->>lre: Start
  else  EP is Resource management system (PBS, Slurm)
    orch->res: Submit Job (component)
    res->>lre: Start
  end

  ...Component starts...
  lre->mon: Subscribe
end

orch-->ide: Started
deactivate orch

ide-->ops: Started
deactivate ide

...Monitoring started...
orch->mon: Query

@enduml
