@startuml

title Monitor Runtime (WP5)

actor "Application\nOps Expert" as ops
participant "SOLIDATE IDE" as ide
participant "Monitoring Dashboard" as dash
participant “Deployment Refactorer” as dr
participant “Monitoring Alert Manager” as alert_mngr
participant  "Monitoring" as monitoring
participant "Exporter" as software
participant "Target Components" as hardware

activate monitoring

loop physical and virtual components
  monitoring->software: collect statistics
  activate software
  software->hardware: probe target
  software->monitoring: provide statistics
  deactivate software
  activate alert_mngr
  monitoring<-alert_mngr: check alert rules
  alert_mngr->dr: trigger monitoring alert
  deactivate alert_mngr
end

alt Standard Stats
  ops->ide: consult standard statistics
  activate ide
  ide->dash: report standard statistics
  activate dash
  dash->monitoring: query standard statistics
  monitoring-->dash: aggregated standard statistics
  deactivate dash
  ide->ops: aggregated standard statistics
else Special Stats
  ops->ide: consult special statistics
  ide->dash: report special statistics
  activate dash
  dash->monitoring: query special statistics
  monitoring-->dash: aggregated / filtered special statistics
  deactivate dash
ide->ops: aggregated / filtered special statistics

deactivate ide
deactivate monitoring
end
@enduml
