@startuml

title Execute Provisioning, Deployment and Configuration (WP5)

actor "Application\nOps Expert" as ops
participant "SOLIDATE\nIDE" as ide
participant "IaC Blueprint Builder" as builder
participant "Image Registry" as imagereg
participant  Orchestrator as orch
participant "Execution Platform\nManager" as res
participant "VM" as VM
participant "Monitoring" as mon


ops->ide: Deploy
activate ide
ide->builder: Save AADM (AADM JSON)
activate builder
builder->builder: Create CSAR
builder->orch: Create blueprint (CSAR + inputs)
activate orch
orch->orch: Save blueprint
orch-->builder: Blueprint created (Blueprint ID)
deactivate orch
builder-->ide: Blueprint created (Blueprint ID)
deactivate builder

ide->orch: Deploy blueprint (Blueprint ID + inputs)
activate orch
orch-->ide: Deployment started (Session ID)
orch->orch: Deploy

loop Execution Platform (EP) in Execution Platforms

  activate res
  alt EP is IaaS Clouds (OpenStack, AWS)
    orch->res: Provision (IaaS resources)
    res-->orch: Set of VMs
    orch->VM: Install Lightweight Runtime Environment (LRE)
  end
  deactivate res

  loop Application components per EP

    orch->imagereg: Pull container image (image name)
    imagereg-->orch: Container image

    alt EP is IaaS Clouds (OpenStack, AWS)
      orch->VM: Deploy (container image)
      orch->VM: Configure (application component + values)
    else EP is Kubernetes
      orch->res: Submit(deployment)
      activate res
        note right
          Kubernetes automates:
          - provision of pods
          - artifact deployment
          - configuration of components
        end note
        res-->orch: deployment created
      deactivate res

    else EP is Resource management system (PBS, Slurm)
      orch->res: Copy artifacts to user workspace
      orch->res: Copy job script to user workspace
    end

    opt
      orch->mon: Configure monitoring
    end

  end
end
deactivate orch

orch-->ide: Deployment complete
deactivate ide

ide-->ops: Deployment complete

@enduml