@startuml

title Start batch application (WP5)

actor "Application\nOps Expert" as ops
participant  Orchestrator as orch
participant "Execution Platform \n (EP)" as res
participant "Component" as lre
participant "Monitoring Platform" as mon

ops->orch: Deploy
activate orch
ref over orch: Check JWT access token
par Startable components
  alt EP is IaaS Clouds (OpenStack, AWS)
    lre->lre: Component started
  else EP is Kubernetes
    lre->lre: Component started
  else  EP is Resource management system (PBS Toque, Slurm)
    orch->res: Submit job (component)
    res->res: Enqueue job
    orch<--res: job id
    activate mon
    orch->mon: subscribe in HPC monitoring probe (job id)
    ...Monitoring started...
    orch->mon: Query
    ... Eventually in future time ...
    res->res: Dequeue job
    res->lre: Run job
    lre->lre: Component started
    lre->lre: Component ended
    deactivate mon
  end

end

deactivate orch
orch-->ops: Deployment complete

@enduml
