@startuml

title Start application (WP5)

actor "Application\nOps Expert" as ops
participant "SODALITE\nIDE" as ide
participant  Orchestrator as orch
participant "Execution Platform" as res
participant "VM" as VM
participant "Component" as lre
participant "Monitoring Platform" as mon

ops->ide: start application(application)

ide->orch: start application(application)
activate ide

activate orch
par startable components
  alt E.P. is OpenStack
    orch->VM: start(component)
    VM->>lre: start
  else E.P. is Kubernetes
    orch->res: start(component)
    res->>lre: start
  else  E.P. is HPC/GPU cluster
    orch->res: submitJob(component)
    res->>lre: start
  end

  ...component starts...
  lre->mon: subscribe
end

orch-->ide: started
deactivate orch

ide-->ops: started
deactivate ide

...monitoring started...
orch->mon: query

@enduml
