@startuml

title Monitor Runtime (WP5)

actor "Application\nOps Expert" as ops

participant "Web Browser" as browser
participant "SOLIDATE IDE" as ide
participant "Monitoring Dashboard" as dash
participant "Dashboard Registry" as registry
participant "Deployment Refactorer" as dr
participant "Monitoring Alert Manager" as alert_mngr
participant "Monitoring" as monitoring
participant "Exporter" as software
participant "Target Components" as hardware

activate monitoring

loop physical and virtual components
  monitoring -> software: collect statistics
  activate software
  software -> hardware: probe target
  software -> monitoring: provide statistics
  deactivate software
  activate alert_mngr
  monitoring <- alert_mngr: check alert rules
  alert_mngr -> dr: trigger monitoring alert
  deactivate alert_mngr
end

ops -> ide: consult metrics
activate ide
ide -> registry: request dashboards
activate registry
registry -> ide: return dashboard URLs
deactivate registry
ide -> ops: present dashboard URLs
deactivate ide

ops -> browser: access dashboard URL
activate browser
browser -> dash: request dashboard
activate dash
dash -> browser: redirect to Keycloak login
ref over browser: Web Login
browser -> ops: Present dashboard

loop 
  dash -> monitoring: query deployment metrics
  monitoring --> dash: deployment metrics
  dash -> ops: aggregated/filtered metrics
end

deactivate dash
deactivate monitoring

@enduml