@startuml

title Verify IaC (WP4)

actor "Application\nOps Expert (AOE)" as ops
participant "SODALITE\nIDE" as sic
participant "IaC Verifier" as soda
participant "Verification\nModel\nBuilder" as vmb
participant "Topology\nVerifier" as tv
participant "Provisioning\nWorkflow\nVerifier" as pwv
participant "Semantic\nKnowledge Base" as kb

ops->sic: verify\n(IaC, Correctness Criteria)
activate sic
sic->soda: verify\n(IaC, Correctness Criteria)
activate soda
soda -> vmb: build Verification\nModels (IaC)
activate vmb
vmb -> kb: retrieve Verification Knowledge
activate kb
kb --> vmb: verification knowledge
deactivate kb
alt Parse and Model Building Errors
    vmb --> soda: Parse and Model\nBuilding Errors
    soda --> sic: Parse and Model\nBuilding Errors
    sic --> ops: Parse and Model\nBuilding Errors
else  Parse and Model Building Success
    vmb --> soda: Verification Models
    deactivate vmb
    soda -> tv: Verify Topology (model, criteria)
    activate tv
    tv --> soda: Verification Results
    deactivate tv
    alt Invalid Topology
        soda --> sic: Topology Verification\nErrors
        sic --> ops: Topology Verification\nErrors
    else Valid Topology
        soda -> pwv: Verify Provisioning Workflow (model, criteria)
        activate pwv
        pwv --> soda: Verification Results
        deactivate pwv
        alt Invalid Provisioning Workflow
            soda --> sic: Provisioning Workflow\nVerification Errors
            sic --> ops: Provisioning Workflow\nVerification Errors
        else  Valid Provisioning Workflow
            soda --> sic: Verification Summary\nfor Provisioning Workflow\nand Topology
            sic --> ops: Verification Summary\nfor Provisioning Workflow\nand Topology
        end
    end
end

deactivate soda
deactivate sic
@enduml
