@startuml

title Platform Discovery Service (WP4)

actor "Resource Expert" as re
participant "SODALITE IDE" as editor
participant "Platform Discovery\nService" as PDS
participant "Semantic\nReasoner" as reasoner
participant "Infrastructure\nresource" as resource
participant "Semantic\nKnowledge Base" as ontology

re->editor: Enter\nusername/password

activate editor
ref over editor: Login

editor->reasoner:  select Application Deployment Project Domain (ADPD) defined
activate reasoner
ref over reasoner: Check JWT access token

reasoner->ontology: Query compatible\nADPD data (SPARQL)
activate ontology
ontology-->reasoner: Return results\nADPD (JSON)
deactivate ontology
reasoner-->editor: Return ADPD (JSON)
deactivate reasoner
editor-->re: Present ADPD data
re->editor: Enter/Select Application Deployment\nProject Domain

loop Select platform
    re->editor: Enter platform acceess details\n(secrets, IPs, keys etc) in JSON key-value format
    'Save the data to secret store as a set of key-value entries (on a uniquiely defined namespace project/platform)
    re->editor: Save\nPlatform Discovery Access Definition <b>(PDAD)

    ref over editor: Save secret (PDAD) in the Vault
    editor->re: Present PDAD save result with PATH (Vault)\nto retrieve saved data from Secret Store

    re->editor: Start discovery process triggers per platform\n(manual,time scheduled,by webhook)

    editor->PDS: Get initial Resource Model\nfor the selected platform\nusing (PATH,JWT)
    activate PDS
    ref over PDS: Read secret (PDAD) from the Vault
    PDS->resource: Get description of the infrastructure\n(using access secrets)
    activate resource
    resource-->PDS: Description of the infrastructure (JSON)
    deactivate resource

    PDS->PDS: Generate TOSCA model from JSON
    PDS->PDS: Generate TTL model for Knowledge Base

    PDS->reasoner: Save Resource Model for the selected\n(project domain, TTL)

    activate reasoner
    ref over reasoner: Check JWT access token
    reasoner->ontology: Save Resource model (SPARQL)
    activate ontology
    ontology-->reasoner: Return save results Resource\nmodel ID (JSON)
    deactivate ontology
    reasoner-->PDS: Resource model ID\nfor the saved resource
    deactivate reasoner

    PDS-->editor: Resource model ID
    deactivate PDS

    editor->reasoner: Get Resource model(RM_ID)
    activate reasoner

    reasoner->ontology: Get Resource model (SPARQL)
    activate ontology
    ontology-->reasoner: Return Resource model (TTL)
    deactivate ontology

    reasoner-->editor: Resource model from (TTL)
    deactivate reasoner
    deactivate PDS

end
@enduml
