@startuml

title Define IaC Bugs Taxonomy (WP4)
actor "Quality Expert" as ops
participant "Bug Predictor and Fixer" as skb

activate ops
ops->ops: Identify Types of Smells, Misconfigurations, and Bugs in IaC
ops->ops: Document Identified Smells, Misconfigurations, and Bugs as Taxonomies 
ops-> ops: Define (Ontological Reasoning) Rules to Detect Smells
ops-> ops: Define (Ontological Reasoning) Rules to Recommend Corrections to Smells
ops -> skb: Deploy Ontological Reasoning Rules 
skb --> ops:
deactivate skb
deactivate ops
@enduml
