@startuml

title Map Resources and Optimisations (WP3)

actor "Quality Expert" as qe
participant "SODALITE IDE" as ide
participant "Semantic Reasoner" as reasoner
participant "Semantic Knowledge Base\n(ontology in GraphDB)" as ontology
participant "Execution Platform" as res
database "IaC Model repository" as iac

qe->ide: Initiate the IDE
activate ide
ide->reasoner: Retrieve known resource types, etc. (API call)
activate reasoner
ref over reasoner: Check JWT access token
reasoner->ontology: Request resources (SPARQL)
activate ontology
ontology->reasoner: Return resources (JSON)
deactivate ontology
reasoner->ide: Return known resource types, etc. (JSON)
deactivate reasoner
ide->qe: Initialization completed - Present design options

loop Design time
    qe->ide: Define a pattern selecting known resource\n types, relationships, etc.
    ide->reasoner: Request validation (API call)
    activate reasoner
    ref over reasoner: Check JWT access token
    reasoner->ontology: Query for known inconsistencies (SPARQL)
    activate ontology
    ontology-->reasoner: Return results (JSON)
    deactivate ontology
    reasoner-->ide: Return detected inconsistencies (JSON)
    deactivate reasoner
    ide-->qe: Present validation results

    opt Optimisations
        qe->ide: Select optimization approach from UI menu
        ide->iac: Get task(ti) information + artifacts
        iac-->ide: Send task metadata and dependencies
        ide->ide: Filter optimisations(Oi) based on application task(ti)
        ide->res: Get available targets(ITi)
        res-->ide: Send all available targets(ITi)
        ide->ide: Filter optimisations(Oi) based on available targets(ITi)
        ide-->qe: Enable filtered optimisations(Oi)
        qe->ide: select Optimisation(Oi) for task(ti) (ti,Oi)
        ide --> qe:  Enable Optimisation settings  (ti,Oi)
        qe  -> ide: Enter Optimisation settings (ti,Oi)
        ide -> ide: Validate Optimisation (ti,Oi,ITi)
        ide -> iac: Add to optimisation recipe (ti,Oi,ITi)
        ide --> qe:  Send Optimisation Report
    end

    opt Mapping of target resources
        qe->ide: Ask to map target resources to abstract pattern
        ide->reasoner: Request known target resources (API call)
        activate reasoner
        ref over reasoner: Check JWT access token
        reasoner->ontology: Query compatible target resources (SPARQL)
        activate ontology
        ontology-->reasoner: Return results (JSON)
        deactivate ontology
        reasoner-->ide: Return target resources (JSON)
        deactivate reasoner
        ide-->qe: Present compatible target resources
        qe->ide: Map target resources to new pattern
        qe->ide: Assign performance metrics
    end
end

qe->ide: Submit new resource pattern,\n optimization parameters,\n target resources and\n performance metrics
ide->reasoner: Request to store new pattern (API call)
activate reasoner
ref over reasoner: Check JWT access token
reasoner->ontology: Store new pattern (SPARQL)
deactivate reasoner

@enduml
