@startuml 

title SODALITE Use Case Diagram

left to right direction

skinparam usecase {
    BackgroundColor LightBlue
    BorderColor DarkSlateGray

    BackgroundColor<< Main >> YellowGreen
    BorderColor<< Main >> YellowGreen

    ArrowColor Black
    ActorBorderColor black
    ActorFontName Courier

    ActorBackgroundColor<< Human >> Gold
}



'Define use cases
rectangle SODALITE {
    (UC1 Define Application\nDeployment Model - WP3) as (DefineApplicationDeploymentModelWP3)
    (UC2 Select Resources - WP3) as (SelectResourcesWP3)
    (UC3 Generate IaC code - WP4) as (GenerateIaCcodeWP4)
    (UC4 Verify IaC - WP4) as (VerifyIaCWP4)
    (UC5 Predict And Correct Bugs - WP4) as (PredictAndCorrectBugsWP4)
    (UC6 Execute Provisioning,\nDeployment And Configuration - WP5) as (ExecuteProvisioningDeploymentAndConfigurationWP5)
    (UC7 Start Application - WP5) as (StartApplicationWP5)
    (UC8 Monitor Runtime - WP5) as (MonitorRuntimeWP5)
    (UC9 Identify Refactoring Options - WP5) as (IdentifyRefactoringOptionsWP5)
    (UC10 Execute Partial Redeployment - WP5) as (ExecutePartialRedeploymentWP5)
    (UC11 Define IaC Bugs Taxonomy - WP4) as (DefineIaCBugsTaxonomyWP4)
    (UC12 Map Resources\nAnd Optimisations - WP3) as (MapResourcesAndOptimisationsWP3)
    (UC13 Model Resources - WP3) as (ModelResourcesWP3)
    (UC14 Estimate Quality Characteristics\n Of Applications And Workload - WP3) as (EstimateQualityCharacteristicsOfApplicationsAndWorkloadWP4)
    (UC15 Statically Optimize Application\nAnd Deployment - WP4) as (StaticallyOptimizeApplicationandDeploymentWP4)
    (UC16 Build Runtime Images - WP4) as (BuildRuntimeImagesWP4)
    (UC17 Platform Discovery - WP4) as (PlatformDiscoveryWP4)
}

'Define user actors
:Application Ops Expert: << Human >> as AppOpsExp
:Resource Expert: << Human >>as ResourceExp
:Quality Expert: << Human >>as QualityExp

'Define resource actors
:Resource: as Resource
:Storage Middleware: as StorageMiddleware
:Communication Middleware: as CommunicationMiddleware
:Middleware: as Middleware
:GPU Cluster: as GPUCluster
:Cloud: as Cloud
:HPC: as HPC
:Execution Platform: as ExecPlatform
:Application Component: as AppComponent

'Define extension/generalization
HPC -up-|> ExecPlatform
Cloud -up-|> ExecPlatform
GPUCluster -up-|> ExecPlatform

CommunicationMiddleware -up-|> Middleware
StorageMiddleware -up-|> Middleware

AppComponent -up-|> Resource
ExecPlatform -up-|> Resource
Middleware -up-|> Resource

'Definition of relations/actions
AppOpsExp --> (DefineApplicationDeploymentModelWP3)
AppOpsExp --> (SelectResourcesWP3)
AppOpsExp --> (GenerateIaCcodeWP4)
AppOpsExp --> (VerifyIaCWP4)
AppOpsExp --> (PredictAndCorrectBugsWP4)
AppOpsExp --> (ExecuteProvisioningDeploymentAndConfigurationWP5)
AppOpsExp --> (StartApplicationWP5)
AppOpsExp --> (MonitorRuntimeWP5)
AppOpsExp --> (IdentifyRefactoringOptionsWP5)
AppOpsExp --> (ExecutePartialRedeploymentWP5)
AppOpsExp -- (StaticallyOptimizeApplicationandDeploymentWP4)
(GenerateIaCcodeWP4) .> (BuildRuntimeImagesWP4): <<include>>

QualityExp --> (DefineIaCBugsTaxonomyWP4)
QualityExp --> (EstimateQualityCharacteristicsOfApplicationsAndWorkloadWP4)
QualityExp --> (MapResourcesAndOptimisationsWP3)

ResourceExp --> (ModelResourcesWP3)
ResourceExp --> (PlatformDiscoveryWP4)

(MapResourcesAndOptimisationsWP3) .> (StaticallyOptimizeApplicationandDeploymentWP4): <<include>>

(ExecuteProvisioningDeploymentAndConfigurationWP5) -- Resource
(MonitorRuntimeWP5) -- Resource
(IdentifyRefactoringOptionsWP5) -- Resource
(ExecutePartialRedeploymentWP5) -- Resource
(EstimateQualityCharacteristicsOfApplicationsAndWorkloadWP4) -- Resource
(StartApplicationWP5) -- Resource
(PlatformDiscoveryWP4) -- Resource

@enduml
