@startmindmap AppOpsExpertUCs

<style>
mindmapDiagram {
  node {
    Padding 15
    Margin 15
    BackGroundColor LightBlue
  }
  rootNode {
    Padding 15
	Margin 15
    BackGroundColor AliceBlue
	FontSize 12
  }
  leafNode {
    Padding 10
    BackGroundColor LightBlue
    FontColor Black
    FontSize 11
  }
}
</style>

* <b>Application</b>\n<b>Ops Expert</b>
left side
** UC1 Define Application\nDeployment Model
** UC2 Select Resources
** UC3 Generate IaC code
** UC4 Verify IaC
** UC5 Predict And\nCorrect Bugs
** UC6 Execute Provisioning,\nDeployment And\nConfiguration

right side
** UC7 Start Application
** UC8 Monitor Runtime
** UC9 Identify\nRefactoring Options 
** UC10 Execute Partial\nRedeployment
** UC15 Statically Optimize\nApplication\nAnd Deployment
** UC16 Build Runtime\nImages

@endmindmap
