@startuml

title SODALITE General Architecture

skinparam fixCircleLabelOverlapping true 
skinparam defaultFontSize 20
skinparam dpi 90

'WP3 modelling layer
[SODALITE\nModeling Layer] as WP3 #PaleGreen
interface "Semantic\nReasonerAPI" as sem #PaleGreen
WP3 -d- sem

'WP4 infrastructure as Code layer
[SODALITE\nInfrastructure as Code Layer] as WP4 #LightSalmon
interface "Deployment\nPreparationAPI" as dep #LightSalmon
interface "DefectPrediction\nCorrectionAPI" as defect #LightSalmon
interface "IaCVerifactionAPI" as verif #LightSalmon
interface "ImageRegistryAPI" as imagereg  #LightSalmon
interface "ImageBuilderAPI" as imagebuilder  #LightSalmon
interface "PlatformDiscoveryAPI" as pds #LightSalmon
WP4 -u- dep
WP4 -u- defect
WP4 -u- verif
WP4 -u- pds
WP4 -d- imagereg
WP4 -u- imagebuilder


'WP4 infrastructure as Code layer
[SODALITE\nRuntime Layer] as WP5 #LightSkyBlue
interface "MonitoringAPI" as mon #LightSkyBlue
interface "OrchestratorAPI" as orch #LightSkyBlue
WP5 -u- mon 
WP5 -u- orch

'security APIs
interface "IAMServiceAPI" as IAMApi #LightSlateGrey
interface "SecretVaultAPI" as VaultAPI #LightSlateGrey

cloud {
    node OpenStack
    node k8s as K8S
    node "PBS/Slurm" as wlm
    node AWS
    node OpenFaaS
}

WP3 -d-( IAMApi
WP3 -d-( VaultAPI
WP3 -d-( dep
WP3 -d-( defect
WP3 -d-( verif
WP3 -d-( mon
WP3 -d-( orch
WP3 -d-( imagebuilder
WP3 -d-( pds

WP4 -u-( IAMApi
WP4 -u-( VaultAPI
WP4 -u-( sem
WP4 -u-( orch

WP5 -u-( IAMApi
WP5 -u-( VaultAPI
WP5 -u-( imagereg
WP5 -r-( dep
WP5 -r-( sem

WP5 .d.> OpenStack
WP5 .d.> K8S
WP5 .d.> wlm
WP5 .d.> AWS
WP5 .d.> OpenFaaS

@enduml
