@startuml

title WP3 Architecture Overview

interface "DeploymentPreparationAPI" as deploymentPreparationAPI
interface "DefectPredictionCorrectionAPI" as correctionAPI
interface "MonitoringAPI" as monitoringAPI
interface "MonitoringRuleAPI" as monitoringRuleAPI
interface "IaCVerificationAPI" as iacverificationAPI
interface "OrchestratorAPI" as orchestratorAPI

package "Platform Discovery Service" as PDS {
    interface "PlatformDiscoveryAPI" as PDSAPI
}

package "SODALITE IDE" as IDE {
    component [DSL Editor] as ideDSLeditor
    component [GUI] as ideGUI
}

package "Semantic Reasoner" as res {
    interface "SemanticReasonerAPI" as resAPI
    component [Semantic Population Engine] as resPopulationEngine
    component [Semantic Reasoning Engine] as resReasoningEngine
}

package "Semantic Knowledge Base" as repo {
    database "RDF Triplestore\n(GraphDB)" as triplestore {
        interface "SPARQL Endpoint" as repoEndpoint
        component [Domain Ontologies] as repoOntologies
    }
}

note left of repoOntologies
   __**Semantic Modelling & Abstraction**__ 
   Application Ontology
   Infrastructure Ontology
   Performance Optimization Ontology
   Deployment & Lifecycle Ontology
end note

resAPI -down- resPopulationEngine
resAPI -up- resReasoningEngine
ideDSLeditor .left.> resAPI: use
ideDSLeditor <-down--> ideGUI
repoOntologies -up- repoEndpoint
resPopulationEngine .left.> repoEndpoint: use
resReasoningEngine .left.> repoEndpoint: use
resPopulationEngine ..> correctionAPI: use
ideGUI ..> deploymentPreparationAPI : use
ideGUI ..> monitoringAPI : use
ideGUI ..> monitoringRuleAPI : use
ideGUI ..> iacverificationAPI : use
ideGUI ..> orchestratorAPI : use
ideGUI ..> PDSAPI : use
PDS .up.> resAPI:use

@enduml