@startuml
hide unlinked
title Save secret in the Vault
participant "SODALITE Endpoint\nClient" as client
participant "Secrets\nVault" as secretstore
participant "IAM" as IAM


activate client
client->secretstore: Save Secret key-value + JWT token (API call)
activate secretstore
secretstore->IAM: check JWT\naccess token
activate IAM
IAM-->secretstore: valid access token
deactivate IAM
secretstore->secretstore: check JWT\nwrite privilege\nto project domain
secretstore-->client: Return saving response (JSON)
deactivate secretstore


@enduml
